USE BATCH202303;

SELECT * FROM MED_2023;

SELECT TOP 100 * FROM MED_2023;

SELECT TOP 10 * FROM MED_2023;

SELECT TOP 10 PERCENT  * FROM MED_2023;
SELECT TOP 100 * FROM MED_2023 ORDER BY NEWID();

SELECT
CUSTOMER_ID,
COMPANY,
GENDER,
AGE,
STATE_CODE,
NO_OF_TRIPS,
SPENT_AMOUNT
INTO MED_NEW_V1
FROM MED_2023;

SELECT *FROM MED_NEW_V1;

SELECT COUNT( DISTINCT COMPANY) FROM MED_2023;

SELECT 'RAJ' AS STU_NAME , 'BTECH' AS EDUCATION,22-03-2022 AS DOE,'TELANGANA' AS STATE INTO MED_2022
UNION ALL
SELECT 'NISHANT' AS STU_NAME , 'MTECH' AS EDUCATION,20-03-2022 AS DOE,'BHUBANESHWAR' AS STATE 
UNION ALL
SELECT 'VISHAL' AS STU_NAME , 'BSC' AS EDUCATION,18-03-2022 AS DOE,'MADHYAPRADESH' AS STATE ;

SELECT * FROM MED_2022;

SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
'AUSTRALIA' AS COUNTRY,
GETDATE() AS TODAY_DATE
FROM MED_2023;


SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE COMPANY='APPOLO';

SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE COMPANY IN ('APPOLO','GENO','GSK');

SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE COMPANY IN ('APPOLO','GENO','GSK') AND GENDER='FEMALE';


SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE COMPANY IN ('APPOLO','GENO','GSK') OR GENDER='FEMALE';

SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE COMPANY NOT IN ('APPOLO','GENO','GSK') OR GENDER='FEMALE';

SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE AGE>50;

SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE AGE=50;


SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE AGE<>50;



SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE SPENT_AMOUNT >=2000;


SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE AGE BETWEEN 30 AND 50 ;


SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE TOWN LIKE 'K%';

SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE TOWN LIKE '%K%';

SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT
FROM MED_2023
WHERE TOWN LIKE 'K_______';


SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT,
(SPENT_AMOUNT/NO_OF_TRIPS) AS AVG_SPENT
FROM MED_2023


SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT,
FORMAT((SPENT_AMOUNT/NO_OF_TRIPS),'C0') AS AVG_SPENT
FROM MED_2023

SELECT 
COMPANY,
GENDER,
AGE,
STATE_CODE,
TOWN,
NO_OF_TRIPS,
SPENT_AMOUNT,
FORMAT((SPENT_AMOUNT/NO_OF_TRIPS),'C2') AS AVG_SPENT
FROM MED_2023



SELECT 
100+100 AS ADDITION,
100-50 AS SUBSTRACTION,
100/20 AS DIVISION,
100*2 AS MULTIPLICATION


SELECT COUNT(*) FROM MED_2023;

SELECT COUNT(CUSTOMER_ID) FROM MED_2023;


SELECT COUNT(CONTACT_PREF) FROM MED_2023;

SELECT SUM(SPENT_AMOUNT) AS TOTAL_SPENT FROM MED_2023;


SELECT FORMAT(AVG(AGE),'N0' )AS AVG_AGE FROM MED_2023;

SELECT FORMAT(SUM(NO_OF_TRIPS),'N0' )AS TOTAL_TRIPS FROM MED_2023;

SELECT FORMAT(MIN(SPENT_AMOUNT),'C0') AS MINUM_SPENT FROM MED_2023;
SELECT FORMAT(MAX(SPENT_AMOUNT),'C0') AS MINUM_SPENT FROM MED_2023;

SELECT * FROM MED_SORT1;

SELECT * FROM STU_SCORE;

SELECT 
STU_NAME,
SUBJECT,
YEAR,
MARKS
FROM STU_SCORE

ORDER BY STU_NAME,SUBJECT;

SELECT 
STU_NAME,
SUBJECT,
YEAR,
MARKS
FROM STU_SCORE
ORDER BY STU_NAME,SUBJECT,YEAR;

SELECT 
SUBJECT,
YEAR,
STU_NAME,
MARKS
FROM STU_SCORE
ORDER BY SUBJECT,STU_NAME,MARKS DESC;

SELECT 
SUBJECT,
YEAR,
STU_NAME,
MARKS
FROM STU_SCORE
ORDER BY 1,3,4 DESC;

SELECT
STATE_CODE,
COMPANY,
SUM(SPENT_AMOUNT) AS TOTAL_SPENT
FROM MED_2023
WHERE COMPANY IN ('APPOLO','CIPLA','GENO')
GROUP BY STATE_CODE,COMPANY 
HAVING SUM(SPENT_AMOUNT) >=10000
ORDER BY 1,2;

--SEQUENCE OF CLAUSE IS 
--WHERE
--GROUP BY
--HAVING
--ORDER BY

--USE OF CASE AND WHEN STATEMENT

SELECT 
CUSTOMER_ID,
COMPANY,
GENDER,
AGE,
CASE
    WHEN AGE>=60 THEN 'OLD-AGE'
	WHEN AGE>=50 THEN 'MID-OLD-AGE'
	WHEN AGE>=40 THEN 'MID-AGE'
	WHEN AGE>=30 THEN 'MID-YOUNG-AGE'
	ELSE 'YOUNG-AGE'
	END AS AGE_BUCKET,

STATE_CODE,
NO_OF_TRIPS,
CASE 
   WHEN NO_OF_TRIPS>=30 THEN 'REGULAR'
   WHEN NO_OF_TRIPS>=10 THEN 'SLOPPY'
   ELSE 'CASUAL'
   END AS VISIT_BUCKET,
SPENT_AMOUNT,
     CASE
	    WHEN SPENT_AMOUNT>=1000 THEN 'PREMIER'
		WHEN SPENT_AMOUNT>= 500 THEN 'ADVANCE'
		ELSE 'RETAL'
		END AS SPENT_BUCKET
FROM MED_2023;

 
--HOW TO UPDATE TABLE

SELECT
CUSTOMER_ID,
COMPANY,
GENDER,
AGE,
STATE_CODE,
SPENT_AMOUNT
INTO MED_UPDATE
FROM MED_2023;

UPDATE MED_UPDATE
SET GENDER ='F'
WHERE GENDER='FEMALE'

UPDATE MED_UPDATE
SET GENDER ='M'
WHERE GENDER='MALE'

UPDATE MED_UPDATE
SET GENDER ='U'
WHERE GENDER='UNISEX'

SELECT * FROM MED_UPDATE;

ALTER TABLE MED_UPDATE
ADD  AGE_BUCKET CHAR(20),SPENT_BUCKET CHAR(20);

SELECT * FROM MED_UPDATE;

UPDATE MED_UPDATE
SET AGE_BUCKET=(CASE
    WHEN AGE>=60 THEN 'OLD-AGE'
	WHEN AGE>=50 THEN 'MID-OLD-AGE'
	WHEN AGE>=40 THEN 'MID-AGE'
	WHEN AGE>=30 THEN 'MID-YOUNG-AGE'
	ELSE 'YOUNG-AGE'
	END );

	
SELECT * FROM MED_UPDATE;


UPDATE MED_UPDATE
SET SPENT_BUCKET=(CASE
	    WHEN SPENT_AMOUNT>=1000 THEN 'PREMIER'
		WHEN SPENT_AMOUNT>= 500 THEN 'ADVANCE'
		ELSE 'RETAL'
		END);

			
SELECT * FROM MED_UPDATE;

--DELETE QUERY

SELECT
CUSTOMER_ID,
COMPANY,
GENDER,
AGE,
STATE_CODE,
SPENT_AMOUNT
INTO MED_DELETE
FROM MED_UPDATE;

SELECT * FROM MED_DELETE;

DELETE MED_DELETE
WHERE COMPANY IN ('APPOLO','CIPLA','GENO');

SELECT DISTINCT COMPANY FROM MED_DELETE;


SELECT COUNT( DISTINCT COMPANY) FROM MED_DELETE;

--SUMMARIZING THE DATA USING CASE AND WHEN STATE STATEMENT


SELECT 
COMPANY ,
COUNT(CASE WHEN GENDER='FEMALE' THEN CUSTOMER_ID END) AS FEMALE_BASE,
COUNT(CASE WHEN GENDER='MALE' THEN CUSTOMER_ID END) AS MALE_BASE,
COUNT(CASE WHEN GENDER='UNISEX' THEN CUSTOMER_ID END) AS UNISEX_BASE
FROM MED_2023
GROUP BY COMPANY;



SELECT 
COMPANY ,
SUM(CASE WHEN GENDER='FEMALE' THEN SPENT_AMOUNT END) AS FEMALE_SPENT,
SUM(CASE WHEN GENDER='MALE' THEN SPENT_AMOUNT END) AS MALE_SPENT,
SUM(CASE WHEN GENDER='UNISEX' THEN SPENT_AMOUNT END) AS UNISEX_SPENT
FROM MED_2023
GROUP BY COMPANY;




SELECT 
COMPANY ,
COUNT(CASE WHEN GENDER='FEMALE' THEN CUSTOMER_ID END) AS FEMALE_BASE,
COUNT(CASE WHEN GENDER='MALE' THEN CUSTOMER_ID END) AS MALE_BASE,
COUNT(CASE WHEN GENDER='UNISEX' THEN CUSTOMER_ID END) AS UNISEX_BASE,
SUM(CASE WHEN GENDER='FEMALE' THEN SPENT_AMOUNT END) AS FEMALE_SPENT,
SUM(CASE WHEN GENDER='MALE' THEN SPENT_AMOUNT END) AS MALE_SPENT,
SUM(CASE WHEN GENDER='UNISEX' THEN SPENT_AMOUNT END) AS UNISEX_SPENT
FROM MED_2023
GROUP BY COMPANY;

SELECT * FROM COMPANY_BASE;

SELECT 
COMPANY,
STATE_CODE,
SCORE
INTO COMPANY_BASE_ALL1
FROM COMPANY_BASE
UNPIVOT (SCORE FOR STATE_CODE IN (ACT,NSW,NT,QLD,SA,VIC,WA)) AS X;

SELECT * FROM COMPANY_BASE_ALL1;

--CONVERTING ROWS INTO INTO COLUMNS
SELECT * FROM COMPANY_BASE;
SELECT 
COMPANY,
ACT,
NSW,
NT,
QLD,
SA,
VIC,
WA
FROM COMPANY_BASE_ALL1 
PIVOT (SUM(SCORE) FOR STATE_CODE IN (ACT,NSW,NT,QLD,SA,VIC,WA)) AS A;

SELECT 
COMPANY,
GENDER,
COUNT(CUSTOMER_ID) AS SUBS
INTO MED_SUMMARY
FROM MED_2023
GROUP BY COMPANY,GENDER
ORDER BY 1,2 ,3 DESC;

SELECT * FROM MED_SUMMARY;


SELECT 
COMPANY,
MALE,
FEMALE,
UNISEX
INTO MED_TRA1
FROM MED_SUMMARY
PIVOT(SUM(SUBS) FOR GENDER IN(MALE,FEMALE,UNISEX)) AS A;

SELECT * FROM MED_TRA1;
SELECT 
COMPANY,
GENDER,
SUBS
FROM MED_TRA1
UNPIVOT (SUBS FOR GENDER IN (MALE,FEMALE,UNISEX)) AS A;


